name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, ADDITIONAL_DEBS: ros-melodic-vision-opencv}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install python3 setuptools
        run: sudo apt-get install python3-setuptools
      - name: Install one-easy-protocol lib
        run: sudo pip3 install one-easy-protocol
      - name: Install neopixel lib
        run: sudo pip3 install rpi_ws281x adafruit-circuitpython-neopixel
      - uses: 'deltarobotone/one_easy_protocol_pkg@master'
      - uses: 'deltarobotone/visy_neopixel_pkg@master'
      - uses: 'deltarobotone/visy_detector_pkg@master'
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
